[package]
name = "lichen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.1"
ngrams = "0.1"
itertools = "0.10"

[build-dependencies]
cc = "1.0"