[package]
name = "lichen"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syntect = "4.6.0"
itertools = "0.10"
clap = "2.34"
onig = { version = "6.0", default-features = false }
walkdir = "2"
rustc-hash = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.11", features = ["base64", "hex"] }
serde_json = "1.0"
postcard = { version = "1.1", features = ["use-std"] }
rand = "0.8"
git-version = "0.3"

[profile.release]
debug = true
opt-level = 3
lto = true
